// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Kontaktperson")]
    public partial class Kontaktperson
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Person { get; set; }
        [Column("TLF")]
        public int Tlf { get; set; }
        [Required]
        [StringLength(30)]
        public string Mail { get; set; }
    }
}