// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Kontaktperson")]
    public partial class Kontaktperson
    {
        [Key]

        [Required(ErrorMessage = "Indtast Id")]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Indtast Navn")]
        public string Person { get; set; }
        
        [Required(ErrorMessage = "Indtast Tlf")]
        public int TLF { get; set; }
        
        [Required(ErrorMessage = "Indtast Mail")]
        public string Mail { get; set; }
        
       
    }
}