// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Udleveringssted")]
    public partial class Udleveringssted
    {
        [Key]

        [Required(ErrorMessage = "Indtast Id")]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Indtast Navn")]
        public string Virksomhed { get; set; }
        
        [Required(ErrorMessage = "Indtast Adresse")]
        public string Adresse { get; set; }
        
      
    }
}